/*
Some form magic
Vanja Gavric 2010
*/

jQuery(document).ready(function(){jQuery('.error').hide();var bkgID = $("#contact p.text-field input#url");bkgID.addClass("faded");$(bkgID).focus(function(){$(this).removeClass("faded");});$(bkgID).blur(function(){ if (bkgID.val() != "http://") { bkgID.removeClass("faded"); }else { $(this).addClass("faded"); }});jQuery(".button").click(function(){jQuery('.error').hide();var filter=/^[a-zA-Z0-9]+[a-zA-Z0-9_.-]+[a-zA-Z0-9_-]+@[a-zA-Z0-9]+[a-zA-Z0-9.-]+[a-zA-Z0-9]+.[a-z]{2,4}$/;var urlFilter=/^(https?|ftp):\/\/(((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)+(\/(([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-f]{2})|[!\$&'\(\)\*\+,;=]|:|@)|\/|\?)*)?$/;var name=jQuery("input#name").val();if(name==""){jQuery("label#name_error1").show();jQuery("input#name").focus();return false;}
else if(name.length<3){jQuery("label#name_error2").show();jQuery("input#name").focus();return false;}
var email=jQuery("input#email").val();if(email==""){jQuery("label#email_error1").show();jQuery("input#email").focus();return false;}
else if(!(filter.test(email))){jQuery("label#email_error2").show();jQuery("input#email").focus();return false;}
var url=jQuery("input#url").val();if(url==""){}else if (url == "http://") { url = "" }
else if(!(urlFilter.test(url))){jQuery("label#url_error").show();jQuery("input#url").focus();return false;}
var comment=jQuery("textarea#comment").val();if(comment==""){jQuery("label#textarea_error1").show();jQuery("textarea#comment").focus();return false;}
else if(comment.length<10){jQuery("label#textarea_error2").show();jQuery("textarea#comment").focus();return false;}
var dataString='name='+name+'&email='+email+'&url='+url+'&comment='+comment;jQuery.ajax({type:"POST",url:"bin/process.php",data:dataString,success:function(){jQuery('#contact_form').html("<div id='message'></div>");jQuery('#message').html("<h2>"+form_h1+"</h2>").append("<p>"+form_p+"</p>").append("<img id='checkmark' src='images/check.png' />").hide().fadeIn(1500,function(){});}});return false;});});