/* Magic to make website going
Vanja Gavric
*/

jQuery.noConflict();jQuery(document).ready(function()
{jQuery("#noscript").css("display","none");jQuery.preloadCssImages();getTwitters('tweet',{id:'iVanja1',count:1,enableLinks:true,ignoreReplies:true,template:'<a href="http://twitter.com/%user_screen_name%/"><img src="%user_profile_image_url%" style="float: left;  margin-top: 5px; margin-right: 5px; position: relative; z-index: 0;" /></a> %text%'});var klik_kontrola=0;jQuery.fn.otvori=function(content){jQuery(this).click(function()
{klik_kontrola++;switch(content)
{case"writer":jQuery("#writer-box").zatvoriC('developer','photographer');jQuery("#writer-box").animate({marginTop:"0px"},400);document.title="Vanja Gavrić is a writer.";break;case"developer":jQuery("#developer-box").zatvoriC('writer','photographer');jQuery("#writer-box").animate({marginTop:"-120px"},500);document.title="Vanja Gavrić is a developer.";break;case"photographer":jQuery("#photographer-box").zatvoriC('writer','developer');jQuery("#writer-box").animate({marginTop:"-240px"},600);document.title="Vanja Gavrić is a photographer.";break;}
jQuery("#"+content+"-box").addClass("selected");jQuery("#"+content+"-box a").addClass("sele");if(klik_kontrola==1)
{jQuery("#wrapper").animate({width:"920px"},200);jQuery("#right").animate({width:"360px"},300);jQuery("#"+content).animate({width:"360px"},300);};});};jQuery.fn.zatvori=function(content){jQuery(this).click(function()
{jQuery("#left").css("marginTop","0");jQuery("#"+content).animate({width:"0px"},200);jQuery("#right").animate({width:"0px"},300);jQuery("#wrapper").animate({width:"561px"},500);jQuery("#"+content+"-box").removeClass("selected");jQuery("#"+content+"-box a").removeClass("sele");jQuery("#writer-box").animate({marginTop:"125px"},400);document.title="Vanja Gavrić - Personal Web";klik_kontrola=0;});};jQuery.fn.zatvoriC=function(content1,content2){jQuery("#"+content1).css("width","0px");jQuery("#"+content2).css("width","0px");klik_kontrola=1;jQuery("#"+content1+"-box").removeClass("selected");jQuery("#"+content2+"-box").removeClass("selected");jQuery("#"+content1+"-box a").removeClass("sele");jQuery("#"+content2+"-box a").removeClass("sele");};jQuery("#slide-down").toggle(function t(){jQuery("#lang").animate
({top:"-21px"},400);jQuery("#strel").css("-webkit-transform","rotate(180deg)");jQuery("#strel").css("-moz-transform","rotate(180deg)");jQuery("#strel").css("transform","rotate(180deg)");},function(){jQuery("#lang").animate
({top:"-41px"},400);jQuery("#strel").css("-webkit-transform","rotate(0deg)");jQuery("#strel").css("-moz-transform","rotate(0deg)");jQuery("#strel").css("transform","rotate(0deg)");});jQuery("a.articles").fancybox({'overlayColor':'#000','overlayOpacity':0.8});jQuery("a.work").fancybox({'overlayColor':'#000','overlayOpacity':0.8});jQuery("a.zoom").fancybox({'overlayColor':'#000','overlayOpacity':0.8});jQuery("a.con").fancybox({'overlayColor':'#000','overlayOpacity':1,'hideOnContentClick':false,'frameWidth':620,'frameHeight':430,overlayShow:true,padding:0,border:0,marginTop:0,overflow:"hidden"});jQuery('#lang li:last-child').hover(function(){jQuery(this).animate
({marginLeft:0},200);},function(){jQuery(this).animate
({marginLeft:"55px"},200);});jQuery('#ie6-error a.close').click(function(){jQuery('#ie6-error').css("display","none");});jQuery("#writer-box").otvori('writer');jQuery("#zatvori1").zatvori('writer');jQuery("#otvori2").otvori('developer');jQuery("#zatvori2").zatvori('developer');jQuery("#otvori3").otvori('photographer');jQuery("#zatvori3").zatvori('photographer');});