<?php
$lang = array(
    'en' => array(
        'salutation' => 'Hi',
        'iAm' => 'I&rsquo;m',
        'scrollDown' => 'Scroll down to learn more about me',
        'whoAmI' => 'a <i>full-stack</i> web developer',
        'loading' => 'Loading',
        'specializing' => 'specializing in',
        'skills' => 'Skills',
        'design' => 'Design',
        'iHaveExperienceWith' => 'I have experience with',
        'various' => 'razno',
        'commandLine' => 'Command line',
        'likePhotos' => '<span>I</span> <span>like</span> <span>to</span> <span>shoot</span> <span>photos</span>',
        'someSay' => 'Some say I am even good at it',
        'didWriting' => 'Did some writing too',
        'clickForArticle' => '<span class="click">click</span>  <span class="tap">tap</span> on article to open PDF',
        'contactMe' => 'Contact me',
        'viaSocial' => 'via social networks',
        'or' => 'or',
        'dropEmail' => 'drop me an e-mail',
        'callSkype' => 'call me on Skype',
        'siteBy' => 'a site by',
        'handmade' => 'Handmade using ecologically sustainable code',
        'old' => 'old',
        'description' => 'Vanja Gavrić is a web developer specializing in front-end. He also enjoys taking photos and occasionaly writes about gadgets.',
        // article names....
    ),
    'hr' => array(
        'salutation' => 'Bok',
        'iAm' => 'Ja sam',
        'scrollDown' => 'Više informacija o meni dolje',
        'whoAmI' => '<i>full-stack</i> web developer',
        'loading' => 'Učitavanje',
        'specializing' => 'orijentiran na',
        'skills' => 'Vještine',
        'design' => 'Dizajn',
        'iHaveExperienceWith' => 'Imam iskustva sa',
        'various' => 'Razno',
        'commandLine' => 'Komandna linija',
        'likePhotos' => '<span>Volim</span> <span>fotkati</span>',
        'someSay' => 'Neki kažu da sam čak i dobar',
        'didWriting' => 'Nešto sam i pisao',
        'clickForArticle' => '<span class="click">kliknite</span>  <span class="tap">tapnite</span> na članak za otvaranje PDF-a',
        'contactMe' => 'Kontaktirajte me',
        'viaSocial' => 'putem društvenih mreža',
        'or' => 'ili',
        'dropEmail' => 'pošaljite mi e-mail',
        'callSkype' => 'nazovite me na Skype',
        'siteBy' => '',
        'handmade' => 'Ručno izrađeno korišteći ekološki prihvatljiv kod',
        'old' => 'stari',
        'description' => 'Vanja Gavrić je web developer orijentiran na front-end. Voli fotografiju i povremeno piše o gadgetima.',

    )
);
?>